### PR TITLE
build system improvements

### PR DESCRIPTION
**Pull request by jsynacek**

### CODE REVIEW

**Comment by jsynacek** [comment]
Yay, I've broken your CI:) The tests should be fixed, as they seem to be requiring the man pages to be built, but xsltproc is not installed.

**Comment by kerolasa** [comment]
The rdisc change is merged, see commit f06ca70849886d997406193a3c1d90850ed419ae.

Second change broke travis, so it is not good enough as-is. Change should be updated to install libxslt-dev in .travis.yml file.

**Comment by kerolasa** [comment]
Hi @jsynacek the second change is fixed and merged to upstream as commit 25b552ec2b43c130c0eca71d0306d01b80e0d7ad. Thank you for patches.

**Comment by jsynacek** [comment]
I'm sorry for being so slow... Thank you!

**Pull request closed without merging**
