### PR TITLE
Clockdiff: fix loop and rtt

### PR DESCRIPTION
**Pull request by 6eh01der**
Fix of #326 

It's almost the same code that was used before [s20190324](https://github.com/iputils/iputils/releases/tag/s20190324) version (look at [s20180629](https://github.com/iputils/iputils/releases/tag/s20180629) ) for situation when diff is less then 1 ms. Additionally it include little fix for avoid return incorrect rtt value (750(187)ms and etc).

### CODE REVIEW

**Comment by yueryoufeng** [comment]
I don't know why the loop has to be executed 50 times.

**Comment by yueryoufeng** [comment]
@6eh01der Is there anything else I need to do with this PR? Or have been waiting?

**Comment by 6eh01der** [comment]
> @6eh01der Is there anything else I need to do with this PR? Or have been waiting?

Just wait when commit will be approved. Or declined)

**Comment by pevik** [comment]
@yueryoufeng @6eh01der I'll try to have look on this tomorrow/this week. But clockdiff is a bit hard for me to test (steps to reproduce is welcome).

**Comment by yueryoufeng** [comment]
Thanks for your reply. on my machine, the two machines are in the same network environment, and they appear probably every 10 times.
@pevik

**Comment by pevik** [comment]
Leaving this for next release.

**Comment by pevik** [comment]
Thanks for your effort. In the end we took https://github.com/iputils/iputils/pull/459.

**Pull request closed without merging**
