### PR TITLE
Dual-stack ping

### PR DESCRIPTION
**Pull request by pavlix**
This pull request provides a number of improvements and finally an implementation of dual-stack ping.

### CODE REVIEW

**Comment by pavlix** [comment]
Wait a bit....

**Comment by pavlix** [comment]
wait a bit...

**Comment by pavlix** [comment]
The dual-stack patch can be IMO extended to work with multiple arguments. I'm working on it.

**Comment by pavlix** [comment]
I made additional changes to maintain behavior of the new dual-stack `ping` as close as possible to the behavior of the legacy IPv4 ping now available as `ping -4`.

**Comment by pavlix** [comment]
Please review. Unfortunately after modifications the three (or so) patches were so interconnected that it was more practical to turn it into a single patch. But the patch (and the new code) is IMO well structured and connects ping and ping6 in a consistent way.

**Comment by okias** [comment]
merged, thank you! :)

**Comment by pavlix** [comment]
Thanks!

**Pull request closed without merging**
