### PR TITLE
Remove legacy tools: ninfod, rarpd, rdisc

### PR DESCRIPTION
**Pull request by pevik**
@iputils/maintainers @jsynacek @nmeyerhans @okias @nmav @vapier @yurchor @neheb @6eh01der @sevan @zenczykowski @floppym FYI, feel free to add your ack.

### CODE REVIEW

**Review by floppym — APPROVED** [review]

**Comment by pevik** [comment]
Minor update in commit message.

**Comment by vapier** [comment]
lgtm

#zombieslayer

**Comment by neheb** [comment]
LGTM

**Review by vapier — APPROVED** [review]

**Comment by sevan** [comment]
ok

**Pull request closed without merging**
