### PR TITLE
doc: Proofreading of rarpd.xml

### PR DESCRIPTION
**Pull request by phkam**
A few suggestions to make the manpage more easy to read

### CODE REVIEW

**Comment by pevik** [comment]
You broke xml, see travis build checks
https://travis-ci.org/iputils/iputils/jobs/605612871
Please fix it.

```
FAILED: doc/rarpd.8 
/usr/bin/xsltproc -o doc/rarpd.8 --nonet --stringparam man.output.quietly 1 --stringparam funcsynopsis.style ansi --stringparam man.th.extra1.suppress 1 --stringparam iputils.version s20190709 ../doc/custom-man.xsl ../doc/rarpd.xml
../doc/rarpd.xml:54: parser error : Opening and ending tag mismatch: para line 40 and refsection
  </refsection>
               ^
../doc/rarpd.xml:184: parser error : Opening and ending tag mismatch: refsection line 36 and refentry
</refentry>
           ^
../doc/rarpd.xml:185: parser error : Premature end of data in tag refentry line 1
unable to parse ../doc/rarpd.xml

[5/47] Compiling C object 'common@sta/iputils_common.c.o'.[K
[6/47] Generating ping.8 with a custom command.[K
ninja: build stopped: subcommand failed.
```

**Comment by phkam** [comment]
@pevik whoops. I'm terribly sorry about this.I unbroke it and pushed again. It checks out now.

**Comment by pevik** [comment]
No big deal :). Thanks for your work.

**Comment by kerolasa** [comment]
Thank you for documentation improvements @phkam change is merged to upstream. Can I wish for more of similar sort of work, this is great stuff.

**Pull request merged**
