### PR TITLE
docs: Add instruction for creating sha256sum.asc

### PR DESCRIPTION
**Pull request by pevik**
Signed file containing sha256sum for *.zip and *.tar.gz

+ cleanup (rename variable, remove &&)

Signed-off-by: Petr Vorel <petr.vorel@gmail.com>

### CODE REVIEW

**Comment by kerolasa** [comment]
While on it add note how to add and/or update public keys in Documentation/project-keys.gpg. For example the following is not in that file.

```
iputils $ git verify-tag s20190709
gpg: Signature made Tue 09 Jul 2019 21:55:49 BST
gpg:                using RSA key 2016FEA4858B1C36B32E833AC0DEC2EE72F33A5F
gpg:                issuer "petr.vorel@gmail.com"
```

**Comment by pevik** [comment]
Thanks for a quick review.
I added my gpg pub key to my github account, that's why github shows "verified". But I guess I need to add it into this file. Can I just merge this as it is (if you agree with the changes) and you (when you have time wrote instructions for `Documentation/project-keys.gpg` (and I follow them for this release)?

**Comment by kerolasa** [comment]
Try creating alternative key ring, and then export it. The following should do what is needed.

```
gpg --no-default-keyring --keyring maintainer-keys.gpg --recv-keys 25999B407FB6A9B701BBF1E40D46FEF7E61DBB46 33C58482C402292D2E3C5C069709F90C3C96FFC8 4807F894E0620EEA 4A8D0987698B0274 4AEE18F83AFDEB23 61D580A74CA9277F 8ED396E37E38D471A00530D3A9553245FDE9B739 9FC5E7B74A45D0DE 2016FEA4858B1C36B32E833AC0DEC2EE72F33A5F

gpg --no-default-keyring --keyring maintainer-keys.gpg  --export --armor --output Documentation/project-keys.gpg
```

**Comment by pevik** [comment]
So the purpose of `Documentation/project-keys.gpg` is to have all maintainer keys, I guess.

**Comment by kerolasa** [comment]
All keys used for signing tags, releases, commits, or such. Just throw all into that file so that verifying check sums is easy and has some legitimacy because the file containing public keys is part of project that is signed with the very same keys. I hope that makes sense.

**Comment by pevik** [comment]
Adding script to update, updated docs and keyring.
Whom belongs this key `61D580A74CA9277F`? I haven't found it (`gpg: keyserver receive failed: No data`).

script: if you like it, I can add more scripts (for releasing). I prefer it than copy pasting from docs).

**Comment by kerolasa** [comment]
Merged. I don't know either what is 61D580A74CA9277F.

**Pull request merged**
