### PR TITLE
Translations update from Fedora Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Fedora Weblate](https://translate.fedoraproject.org) for [iputils/iputils](https://translate.fedoraproject.org/projects/iputils/iputils/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by pevik** [comment]
Not much translated (just single string declared as not fuzzy - user invisible change), thus closing for now (will be waiting in https://translate.fedoraproject.org/projects/iputils/iputils/ git repository for more updates).

**Comment by marek22k** [comment]
I have created some [German translations](https://github.com/iputils/iputils/commit/7fee1ca78e32abf8bac67ea6d1c00cd8cbe8eddf) (no idea how well I did). Maybe they can be merged before the next release?

**Comment by pevik** [comment]
@marek22k Don't worry, I merged your work here: 6cbbf26d1317108c3b26e0f4eec885f64b6a20a9.
I'm normally rebasing the changes + add mine and the author sign-off tag, thus the hash is different.

I'm sorry, for the confusion, I should mention that my comment was for French translation (this commit: fbbf75a7704b4a444625c0e9c314970a840dd6dc) which really did not contain anything user visible. Because when I closed the project, it was after I merged other translations, including your German one.

**Comment by pevik** [comment]
FYI so far merged 6 language updates: e7822419511c2bf7dfec83c856245c51f4748455, e56df5e01a3102996df53f5f7b5742034d995a0f, 852ab40fd80898e606cabb795ea8cb3f79c557fa, 5149b0e3f5e11bbc816c6ff749f07a663e353d78, 6cbbf26d1317108c3b26e0f4eec885f64b6a20a9,6d52ad313ee215f339a4376876e30427a012415c.

**Pull request closed without merging**
