### PR TITLE
arping: make usage output consistent with man page

### PR DESCRIPTION
**Pull request by jsynacek**

### CODE REVIEW

**Comment by jsynacek** [comment]
This patch is actually not correct. The -I option has to be used only when the device isn't decided automatically. The error message given by the program is unfortunate, though. I'll post a better patch.

**Comment by okias** [comment]
Should I close it?

**Comment by jsynacek** [comment]
I'll follow up with a patch and close it then.

**Comment by jsynacek** [comment]
v2: https://github.com/iputils/iputils/pull/64

**Pull request closed without merging**
