### PR TITLE
ping:fix ping dead loop problem

### PR DESCRIPTION
**Pull request by lac-0073**
It would be stuck during ping if i modify the current time to the previous time ,and will not exit normally
fix the issues #276

### CODE REVIEW

**Comment by pevik** [comment]
You can use single pull request and use `git push -f` to update it (instead opening several pull requests for single ticket).

**Comment by pevik** [comment]
Ideally describe the problem in the commit message, use `Fixes: #276` in the commit message, correct typos in the commit message.

**Comment by lac-0073** [comment]
> Ideally describe the problem in the commit message, use `Fixes: #276` in the commit message, correct typos in the commit message.

Thanks for  the heads-up,  I've revised it as you suggested.

**Comment by kerolasa** [comment]
Merged with a little bit modified commit message, see 4fd276cd8211c502cb87c5db0ce15cd685177216. Thank you for contribution @lac-0073

**Pull request closed without merging**
