### PR TITLE
Print 5837 extensions in traceroute6

### PR DESCRIPTION
**Pull request by Ishaangandhi**
[RFC 5837](https://tools.ietf.org/html/rfc5837#section-3.1) extends ICMP to provide more information about the interfaces packets move through as they flow through the network.

This patch prints those extensions when traceroute6 is run in verbose mode.

Example usage:
```
alfredo@alfredo-XPS-13-9365:~/ishaan/iputils$ traceroute6 -v 2600::
traceroute to 2600:: (2600::) from 2600:8801:130a:ce00:3da8:5100:3df4:65f1, 30 hops max, 24 byte packets
 1  2600:8801:130a:ce00:41c9:d919:7bc8:3223 (2600:8801:130a:ce00:41c9:d919:7bc8:3223)
	Arrival interface: if index=2; address=2600:8801:130a:ce00::da2c; name=wlp4s0; mtu=1500;
  588.2737 ms  155.0220 ms  5.0975 ms
 2  2600:8801:130a:ce00:9a9d:5dff:fe0b:ff1b (2600:8801:130a:ce00:9a9d:5dff:fe0b:ff1b)  6.8791 ms  9.2554 ms  6.3544 ms
 3  2600:8801:137f:ffff::1111 (2600:8801:137f:ffff::1111)  13.7285 ms  13.7895 ms  13.7774 ms
```
Signed-off-by: Ishaan Gandhi <ishaangandhi@gmail.com>

### CODE REVIEW

**Comment by pevik** [comment]
On a first quick look LGTM, but I'll need more time for review. 
nit: you could be consistent with brackets (`{` should be on the same line), and avoid brackets on single statement in if.

**Comment by pevik** [comment]
Also please add info in PR also to the commit message.

**Comment by pevik** [comment]
I'm trying to test it on google.com IPv6 address, but I always get return on `if (orig_datagram_len == 0)`. Could you please provide how to test this (ideally using netns thus it's always reproducible).

BTW did you think to submit RFC 5837 support to `tracepath` and Dmitry Butskoy's `traceroute` (http://traceroute.sourceforge.net/, seems to be dead, but it's recommended over our `traceroute6`).

Also, I'd like function names to be a bit more consistent (`pr_role()` would be probably `print_role()`), but that's a tiny detail.

**Comment by Ishaangandhi** [comment]
All great questions. Responses inline.

> I'm trying to test it on google.com IPv6 address, but I always get return on `if (orig_datagram_len == 0)`. Could you please provide how to test this (ideally using netns thus it's always reproducible).

RFC 5837 is not widely deployed in many routes today. It will gain more support over the next few years as more routers have large, parallel links (400+ gbps) via multiple interfaces. I wrote an implementation of 5837 in the Linux kernel, installed it on a machine, added custom routes on a test computer via the modified kernel, and send a traceroute6 out via that.

I would be happy to provide the kernel patch, if you're interested in running the tests yourself.

> BTW did you think to submit RFC 5837 support to `tracepath` and Dmitry Butskoy's `traceroute` (http://traceroute.sourceforge.net/, seems to be dead, but it's recommended over our `traceroute6`).

Yes, I am working on `tracepath` right now, I wanted to get this patch merged before submitting that patch.

I hadn't heard of Butskoy's traceroute, I'll check that out.

> Also, I'd like function names to be a bit more consistent (`pr_role()` would be probably `print_role()`), but that's a tiny detail.

Sure, I'd be happy to change that name. (FWIW, `pr_role` was chosen to be consistent with `pr_type`, which was already defined in this code. Would you still like it changed?) Are there any other function names you'd prefer changed?

**Comment by pevik** [comment]
> I would be happy to provide the kernel patch, if you're interested in running the tests yourself.

Yes, please.

> Sure, I'd be happy to change that name. (FWIW, `pr_role` was chosen to be consistent with `pr_type`, which was already defined in this code. Would you still like it changed?) Are there any other function names you'd prefer changed?

You're right, it make sense to keep it `pr_role`.

I'm sorry, it might take some time to review that (overloaded with other projects).

**Comment by Ishaangandhi** [comment]
> > I would be happy to provide the kernel patch, if you're interested in running the tests yourself.
> 
> Yes, please.

Attached at bottom. 

[0001-v3-icmp-support-rfc5837.patch.txt](https://github.com/iputils/iputils/files/6315456/0001-v3-icmp-support-rfc5837.patch.txt)

You can apply this patch on top of Linux 5.9+

> I'm sorry, it might take some time to review that (overloaded with other projects).

That's ok! I will say, my organization and I would _love_ to have this merged into IP Utils by the end of this month. Is there anything I can do to help you review?

**Comment by nmeyerhans** [comment]
> > > I would be happy to provide the kernel patch, if you're interested in running the tests yourself.
> > 
> > 
> > Yes, please.
> 
> [0001-v3-icmp-support-rfc5837.patch.txt](https://github.com/iputils/iputils/files/6315456/0001-v3-icmp-support-rfc5837.patch.txt)
> 
> You can apply this patch on top of Linux 5.9+

Based on the [netdev thread](https://lore.kernel.org/netdev/20210317221959.4410-1-ishaangandhi@gmail.com/), it's not clear that this patch is going to get merged into Linux. That means it'll be hard to integrate functional tests for this into most existing CI services. It also means that we may need to run a locally patched kernel indefinitely in order to keep testing this application feature. That's possible, obviously, but not necessarily ideal over the long term. It'd be really nice to have some public infrastructure against which ad-hoc tests can run.

**Comment by Ishaangandhi** [comment]
I see. Is there anything I can do to help?

**Comment by nmeyerhans** [comment]
> I see. Is there anything I can do to help?

Juniper indicated in the netdev thread that they believe the feature will be more widely deployed in networking infrastructure. Maybe they could provide a publicly reachable network with this feature enabled. This sort of interoperability testing is important when developing network protocols and tools, as I'm sure they well understand.

**Comment by Ishaangandhi** [comment]
Ok, I will see what Juniper says.

In the meantime, prefer this patch for testing:

[0001-v4-icmp-support-rfc5837.patch.txt](https://github.com/iputils/iputils/files/6346135/0001-v4-icmp-support-rfc5837.patch.txt)

**Comment by ValZapod** [comment]
> means it'll be hard to integrate functional tests for this into most existing CI services. It also means that we may need to run a locally patched kernel

What?? I mean it is possible to do a binary patch in memory, but this is insane. Is this the case of unit tests just for unit tests?

**Comment by pevik** [comment]
> What?? I mean it is possible to do a binary patch in memory, but this is insane. Is this the case of unit tests just for unit tests?

@ValZapod FYI I'm planning to write testsuite based on LTP testsuite (https://github.com/iputils/iputils/issues/243). We need it as new development introduced many regressions. And I certainly don't want code which cannot be easily tested.

**Comment by pevik** [comment]
Closing as we removed traceroute6 in a1394212fd4b3e3259104467d9861909961b219e.

**Pull request closed without merging**
