### PR TITLE
deprecate autotools in favour of meson

### PR DESCRIPTION
**Pull request by kerolasa**
New year, new build system. This pull request removes autotools and replaces it with meson. As far I can tell all should work, including stuff like ninja dist. I admit manual creation is printing all sorts of warnings, but they were there earlier. If I some  day figure out how to docbook another pull request  will fix these.

For people who are unfamiliar with meson I added ./configure and Makefile to get going. These do bare minimum, but should give just enough hint how to go about when starting from zero. Perhaps in few years these become unnecessary, meanwhile what ever makes building easy should be favoured.

Let me know if changes to pull are needed. I'm sure travis will tell if I got something wrong with it.

### CODE REVIEW

**Comment by kerolasa** [comment]
Oh my. Docbook urls no reachable from travis. I'll fix that later (this weekend).

**Comment by kerolasa** [comment]
Travis is ok. Human feedback welcome.

**Comment by okias** [comment]
Definitely cool (quick mobile walkthrough)!
Sorry, review and testing will take longer, since I'm moving this month to new place.

Maybe @jsynacek or @pavlix can lay on it meanwhile?

**Comment by kerolasa** [comment]
No problems, try not to break stuff while moving.

FYI When this is reviewed I'll submit more changes. See 'compilation-issues' and 'cleanups' branches from my remote.

https://github.com/kerolasa/iputils/commits/compilation-issues
https://github.com/kerolasa/iputils/commits/cleanups

I can imagine lack of the compilation-issues branch, that will fix all compiler warnings, will quickly start to annoy when reviewing meson build. Well, the warnings annoyed me to the point of I had to fix them - but I don't want to mix these things in same pull request. This build-sys stuff is enough for one pull.

**Comment by okias** [comment]
look good, maybe also ask some MUSL guys if it works for them without compilations errors

**Comment by kerolasa** [comment]
MUSL guys, if assuming no objections by 2018-10-15 this pull will be merged.

**Comment by kerolasa** [comment]
BTW test compilation with archlinux musl worked without issues.

```
Name            : musl
Version         : 1.1.20-1
Description     : Lightweight implementation of C standard library
Architecture    : x86_64
```

**Comment by kerolasa** [comment]
Correction, build is broken. Earlier comment was a build in unrelated project that I build with musl successfully, and I accidentally mixed up terminal windows.

Now when validating I did not get any of the tags work when trying with musl. Has this project ever worked when compiling with musl? Maybe installing musl package and running musl-gcc or musl-clang is not valid test.  I don't know, musl hasn't ever been part of my testing.

**Comment by okias** [comment]
just chroot into some alpine linux and try compile or ask on #musl irc channel, I made iputils compatible before, so it should work

**Pull request merged**
