### PR TITLE
Fix build on MUSL

### PR DESCRIPTION
**Pull request by Whissi**
Add missing AI_IDN and NI_IDN declarations.

Bug: https://bugs.gentoo.org/503914

### CODE REVIEW

**Comment by okias** [comment]
Please rebase a top of latest IDN2 changes! Thank you 👍

**Comment by Whissi** [comment]
Rebased like requested, but see issue #117 first. Looks like there's a general problem on musl with idn (not just with idn2, previous version shows same problem).

**Comment by prometheanfire** [comment]
ya, this patch is required if using IDN on musl, but also causes runtime failures.

**Comment by okias** [comment]
@prometheanfire can you be more specific about runtime failures on MUSL? Thanks

**Comment by pevik** [comment]
@yvs2014 Thanks for a bug report. Could you please create a separate issue? (ideally with a simple reproducer)

**Comment by pevik** [comment]
> <s>@yvs2014 Thanks for a bug report. Could you please create a separate issue? (ideally with a simple reproducer)</s>

I see you have already done it. Thank you!

**Pull request merged**
