### PR TITLE
Transparent support of IPv6 in ping

### PR DESCRIPTION
**Pull request by nmav**
That patch set merges the two tools, keeping them as separate as possible. The approach is hackish but seems to do the trick.

### CODE REVIEW

**Comment by nmav** [comment]
That's a quite hard to understand tool due to several global variables in use. I've tried to limit them, but there are way too many. I'd appreciate a review in case something was missed.

**Comment by pavlix** [comment]
So far I read through the changes and all of them look good. I have some more ideas but let's consider them when the basic patchset is merged.

**Comment by pavlix** [comment]
The changes look good to me.

**Comment by okias** [comment]
Could you please rebase a top of latest changes? (now we're in parity with latest YH-iputils commits).

**Comment by nmav** [comment]
Not really. The new changes introduce yet another global variable.

**Comment by nmav** [comment]
I'll check whether I can make a new pull request.

**Comment by nmav** [comment]
created #19

**Pull request closed without merging**
