### PR TITLE
fix arping -U update arp tables

### PR DESCRIPTION
**Pull request by lac-0073**
fix https://github.com/iputils/iputils/issues/298

### CODE REVIEW

**Comment by kerolasa** [comment]
Change looks promising. Commit message should tell what is the problem this change attempts to fix, and how to reproduce the issue. Sure that is mostly the same what is already in the issue ticket, but I am suspicious of external systems - git history is for ever, while git hosting websites might disappear.

**Comment by pevik** [comment]
Yes, please, put everything into the commit message.

Also, other details of the commit message:
* there should be `Signed-off-by: Your Name <your@email>`
* instead of fix: #298 use Fixes: #298

**Comment by lac-0073** [comment]
> Change looks promising. Commit message should tell what is the problem this change attempts to fix, and how to reproduce the issue. Sure that is mostly the same what is already in the issue ticket, but I am suspicious of external systems - git history is for ever, while git hosting websites might disappear.

thanks ,  I have modified

**Comment by kerolasa** [comment]
Merged with changes 86ed08936d49e2c81ef49dfbd02aca1c74d0c098 thank you for contribution @lac-0073

**Pull request closed without merging**
