### PR TITLE
[RFC] Remove traceroute6

### PR DESCRIPTION
**Pull request by pevik**
Lets drop software which does not make much sense to carry out.

NOTE: later something else to remove? I'd suggest `tftpd` (`dnsmasq` has much better alternative) and consider also `rarpd`, `rdisc`.

### CODE REVIEW

**Comment by pevik** [comment]
@6eh01der @sevan @zenczykowski @floppym @nmav @vapier @yurchor @neheb FYI

**Comment by zenczykowski** [comment]
Probably ifenslave too - ip should be used instead.

**Comment by pevik** [comment]
> Probably `ifenslave; too - ip should be used instead.

`ifenslave` is not from iputils.

**Comment by zenczykowski** [comment]
# rpm -q --filesbypkg iputils-20210202-2.fc34.x86_64 | egrep bin
iputils                   /usr/bin/arping
iputils                   /usr/bin/clockdiff
iputils                   /usr/bin/ping
iputils                   /usr/bin/tracepath
iputils                   /usr/sbin/arping
iputils                   /usr/sbin/ifenslave
iputils                   /usr/sbin/ping
iputils                   /usr/sbin/ping6
iputils                   /usr/sbin/rdisc
iputils                   /usr/sbin/tracepath
iputils                   /usr/sbin/tracepath6

**Comment by pevik** [comment]
That's fedora downstream specific, it has never been part of iputils upstream.
https://src.fedoraproject.org/rpms/iputils/blob/rawhide/f/iputils.spec#_13
https://src.fedoraproject.org/rpms/iputils/blob/rawhide/f/sources
https://src.fedoraproject.org/lookaside/pkgs/iputils/ifenslave.tar.gz/6702c58e970e6a73fc8d9b7c9b63af35/ifenslave.tar.gz

**Comment by nmeyerhans** [comment]
I'm in favor of dropping traceroute6.

I'd also be in favor of dropping tftpd and ninfod. Possibly rarpd and rdisc as well, but I'm familiar with the quality of the alternatives.

**Comment by okias** [comment]
I would propose link to suitable replacement solution from build process, when traceroute6 will be requested

**Review by nmeyerhans — APPROVED** [review]

**Comment by neheb** [comment]
Fine with me.

**Comment by pevik** [comment]
Thanks! I'll wait few more days before removing it. I also created separated ticket to move the discussion there.

**Pull request closed without merging**
