### PR TITLE
Patches

### PR DESCRIPTION
**Pull request by pavlix**
Patches for review and inclusion. I'm sharing the link, so let's give people a bit of time to check the code and functionality.

### CODE REVIEW

**Comment by okias** [comment]
Can you check travis logs, why your changes wont build?

**Comment by okias** [comment]
Thank you! :)

**Comment by dlight** [comment]
Could you release a new iputils version with this bugfix? The last version (s20150815) is from August 2015..

**Comment by okias** [comment]
@dlight Thank you for remainding, RELEASED :) Enjoy

**Pull request merged**
