### PR TITLE
ping: connmark is unsigned int, not signed

### PR DESCRIPTION
**Pull request by luizluca**
See: https://github.com/torvalds/linux/blob/master/include/uapi/linux/netfilter/xt_connmark.h

Signed-off-by: Luiz Angelo Daros de Luca <luizluca@gmail.com>

### CODE REVIEW

**Review by nmeyerhans — APPROVED** [review]
LGTM

**Comment by luizluca** [comment]
Rebased and signed the commit

**Comment by pevik** [comment]
Well, `SO_MARK` is `__u32 sk_mark`, i.e. `uint32_t` in userspace. I'm not sure if `unsigned int` is 4 bytes on all platforms.
And therefore not sure if `UINT32_MAX` is always the same on all platforms, thus maybe check for 4294967295 (the value of `UINT32_MAX` on x86_64).

**Comment by metan-ucw** [comment]
Agree with @luizluca here I do not think that we have to worry about UINT_MAX not being 32bit on Linux. So this can go in as it is and the code could be cleaned up to use the stdint.h types later on.

**Pull request closed without merging**
